Home/urls.py
from django.conf.urls import url
from .views import home,abilities,experience2,experience,form,contact,schedule,add_activity,listAct, delete
app_name= 'Home'
urlpatterns = [
 url(r'^$', home, name='home'),
 url(r'^abilities', abilities, name='abilities'),
 url(r'^experience2', experience2, name='experience2'),
 url(r'^experience', experience, name='experience'),
 url(r'^contact', contact, name='contact'),
 url(r'^form', form, name='form'),
 url(r'^schedule', schedule, name='schedule'),
 url(r'^listAct', listAct, name='listAct'),
 url(r'^add_activity', add_activity, name='add_activity'),
  url(r'^delete', delete, name='delete'),
 
 
]

pepew/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Home.views import home as index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Home/', include('Home.urls', namespace="Home")),
    url(r'^$', index, name='index')

]

Home/models.py
from django.db import models
from datetime import datetime 
# Create your models here.
class Activities(models.Model):
    activity = models.CharField(max_length=20)
    type_act= models.CharField(max_length=20)
    place= models.CharField(max_length=20)
    date = models.CharField(max_length=100)
    

Home/forms.py
from django import forms
from .models import Activities
class Message_Form(forms.Form):
    attrs= {Activities:Activities}
    activity = forms.CharField(label='Activities:', required=True, max_length=27,widget=forms.TextInput(attrs=attrs))
    type_act = forms.CharField(label= 'Type of Activities',required=True,max_length=27,widget=forms.TextInput(attrs=attrs))
    place = forms.CharField(label='Place',required=True,max_length=27, widget=forms.TextInput(attrs=attrs))
    date = forms.DateTimeField(label='Date',required=True, widget=forms.DateTimeInput(attrs={'type':'datetime-local'}),input_formats=['%Y-%m-%dT%H:%M'])

Home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Activities
from datetime import datetime
from .forms import Message_Form
response={}

def home(request):
    return render(request, "Home.html")
def abilities(request):
    return render(request, "Abilities.html")
def experience(request):
    return render(request, "Experience.html")
def experience2(request):
    return render(request, "Experience2.html")
def contact(request):
    return render(request, "Contact.html")
def form(request):
    return render(request, "Form.html")

def schedule(request):
    response['form']= Message_Form
    return render(request, 'Schedule.html', response)


def listAct(request):
    message = Activities.objects.all()
    response['message'] = message
    return render (request, "listActivities.html", response)

def add_activity(request):
    form= Message_Form(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        activity = request.POST['activity']
        type_act= request.POST['type_act']
        place= request.POST['place']
        date= request.POST['date']
        dt = datetime.strptime(date, '%Y-%m-%dT%H:%M')
        activities= Activities(activity=activity,type_act=type_act,place=place,date= dt.strftime("%A, %d %B %Y %I:%M%p"))
        activities.save()
        return redirect('Home:listAct')
    else:
        return redirect('Home:schedule',)

def delete(request):
    message = Activities.objects.all().delete()
    response['message'] = message
    return redirect('Home:listAct')

Home/templates/Abilities.html
<!DOCTYPE html>
<html lang="en">
<header> {% include "partials/header.html" %} </header> 

<body data-spy="scroll" data-target="#navbar" data-offset="50">
<h1 style="margin-top:50px; " align="center">Abilities</h1>
<center>
<div style="margin-top:75px; font-size:18px;" class="Box">
	<h4>Skills</h4>
		<table>
		<tr>
		<td>Java
		<td><img src="https://image.ibb.co/kzm9CK/Capture.png" alt="Capture" border="0">
		
		<td>Excel
		<td><img src="https://image.ibb.co/kzm9CK/Capture.png" alt="Capture" border="0">
		<tr>
		<td>Python
		<td><img src="https://image.ibb.co/kzm9CK/Capture.png" alt="Capture" border="0">
		
		<td>Inovative
		<td><img src="https://image.ibb.co/kzm9CK/Capture.png" alt="Capture" border="0">
		<tr>
		<td>HTML
		<td><img src="https://image.ibb.co/kzm9CK/Capture.png" alt="Capture" border="0">
		
		<td>Speaking
		<td><img src="https://image.ibb.co/kzm9CK/Capture.png" alt="Capture" border="0">
		</table>
	<br>
	<h4>Languages</h4>
	<table>
		<tr>
		<td>Indonesia
		<td><img src="https://image.ibb.co/kzm9CK/Capture.png" alt="Capture" border="0">
		<td>
		<td>English
		<td><img src="https://image.ibb.co/kzm9CK/Capture.png" alt="Capture" border="0">
		<tr>
	</table	>
	</div>
<center>

</body>
<br>
<br>
<br>
<br>
<br>
<br>

</html>

Home/templates/Contact.html
<!DOCTYPE html>
<html lang="en">
<header> {% include "partials/header.html" %} </header> 

<body data-spy="scroll" data-target="#navbar" data-offset="50">
<center>
<h1 style="margin-top:50px">Contact Me<h1>
<div style="margin-top:100px" class= "pict">
<a href="https://www.facebook.com/ali.haddad.733#_"><img src="https://image.ibb.co/fgduU9/fb_icon.jpg" width=250px style="border-radius:500px;" ></a>
<a href="https://plus.google.com/u/0/110075030997922728541?tab=wX"><img src="https://image.ibb.co/egdZxU/google_plus.png" style="border-radius:500px;" width=250px ></a>
<a href="https://www.linkedin.com/in/ali-yusuf-419556159/"><img src="https://image.ibb.co/gDvPU9/if_Linked_In_3138898.png" style="border-radius:500px;" width=250px></a>
</div>
<br>
<a href="{% url 'Home:form' %}" class="Box" style="padding:10px; text-decoration:none; color:black"><strong>Feedback</strong></a>
<br>
</body>

</html>
	

Home/templates/Experience.html
<!DOCTYPE html>
<html lang="en">
<header> {% include "partials/header.html" %} </header> 

<body data-spy="scroll" data-target="#navbar" data-offset="50">
<h1 align="center"  style="margin-top:50px;"> Experiences</h1>
<center>
<br>
<br>
<a class="ToggleActive"><strong>Education</strong></a>
<a class="ToggleDeactive" href="{% url 'Home:experience2' %}" >Careers</a>

<ul class="Box" >
  <li><strong>University of Indonesia</strong><br>2017-Present</li>
  <li><strong>SMAN 61 Jakarta</strong><br>2014-2017</li>
  <li><strong>SMPN 27 Jakarta</strong><br>2011-2014</li>
  <li><strong>SDN 04 Jakarta</strong><br>2005-2011</li>
</ul>
</center>
</body>
<br>
<br>
<br>
<br>
<br>
<br>

</html>

Home/templates/Experience2.html
<!DOCTYPE html>
<html lang="en">
<header> {% include "partials/header.html" %} </header> 

<body data-spy="scroll" data-target="#navbar" data-offset="50">
<h1 align="center" style="margin-top:50px"> Experiences</h1>
<center>
<br>
<br>
<a  class="ToggleDeactive"  href="{% url 'Home:experience' %}" >Education</a>
<a  class="ToggleActive"><strong>Careers</strong></a>

<ul class="Box">
  <li><strong>Staff of Supervisor DPM Fasilkom</strong><br>2018-Present</li>
  <li><strong>VPJ Equipment Open House Fasilkom</strong><br>2018-Present</li>
  <li><strong>Mentor OKK UI</strong><br>2018-2018</li>
 <li><strong>MIUI Beta Tester</strong><br>2016-2016</li>
</ul>
</center>

</body>
<br>
<br>
<br>
<br>
<br>
<br>

</html>

Home/templates/Form.html
<!DOCTYPE html>
<html lang="en">
<header> {% include "partials/header.html" %} </header> 

<body data-spy="scroll" data-target="#navbar" data-offset="50">
<center>
<form class="Box" style="font-size:15px; margin-top:80px">
  <strong>Feedback</strong><br><br>
  Name:<br>
  <input class="form" type="text" name="name" placeholder="Your name" required>
  <br>
  Birth day:<br>
  <input class="form" type="date" name="bday" required><br>
  Email:<br>
  <input class="form" type="email" name="email" placeholder="youremail@mail.com" required>
  <br>
  Subject:<br>
  <input class="form" type="text" name="name" placeholder="Your subject" required>
  <br>
  Message:<br>
  <textarea class="form" rows="4" cols="20" placeholder="Your message...."> </textarea>
  <br><br>
  <input class="form" style="width:100px" type="submit">
</form> 
</body>

</html>

Home/templates/Home.html
<!DOCTYPE html>
<html lang="en">
<header> {% include "partials/header.html" %} </header> 
<body data-spy="scroll" data-target="#navbar" data-offset="50">
<center>
<a href="#section1"><img  src="https://preview.ibb.co/gw0P0K/IMG_20180630_152039_2.jpg" alt="IMG_20180630_152039" align="middle"  width="250" height="250" style="border-radius:180px; margin-top:100px"></a>
<h1 style="margin-top:20px;font-size:40px">Hello..<br>My name is Ali..</h1>
	
	<div id="section1" align="center" style="margin-top:150px; font-size:40px; margin-bottom:60px"> 
          <h1 style="font-size:40px">About Me</h1>	
        </div>
	<a><img src="https://preview.ibb.co/gw0P0K/IMG_20180630_152039_2.jpg" alt="IMG_20180630_152039" align="middle"  width="250" height="250" style="border-radius:180px;"></td></a>
	
	<div id="paragraph" style="margin-top:30px">
	<a style="font-size:18px"> 
		My name is Ali Yusuf, i was born on 20th October
	1999 and grown up in DKI Jakarta. I was studying 
	at University of Indonesia, majoring in Informatics
	Systems at the Faculty of Computer Science. In my 
	family, i am the only person who has different 
	education path.  I am an innovative person, who has 
	full of ideas and  hard worker. I really love everything
	about technology, because its endless and always evolve.
	My goal in the future is making people around me more 
	know about technology and using it with positive ways</a></div>
    
</center >
</body>

</html>

Home/templates/Schedule.html
<!DOCTYPE html>
<html lang="en">
<header> {% include "partials/header.html" %} </header> 
<body data-spy="scroll" data-target="#navbar" data-offset="50">
<center>
<h1 style="margin-top:50px"> My Activity</h1>
<form class="Box" style="width:300px; margin-top:3px" method="POST" action='add_activity' > 
{% csrf_token %} 
{{ form }} 
<br> <br>
<button type="submit" class="btn btn-default">Submit</button> 
</form>
<br> 
<a href="{% url 'Home:listAct' %}"><button  class="btn btn-default">See My Activities</button> </a>
</body>

</html>

Home/templates/listActivities.html
<!DOCTYPE html>
<html lang="en">
<header> {% include "partials/header.html" %} </header> 
<body data-spy="scroll" data-target="#navbar" data-offset="50">
<center>
<h1 style="margin-top:50px"> My Activity</h1>
	<div style="margin-top:40px">
        <table align="center" style="text-align: center;  padding:100px">
            <tr  id='table'>
                <th id='table'>Activities</th>
                <th id='table'>Type of Activities</th>
				<th id='table'>Place</th>
				<th id='table'>Date</th>
            </tr>

            	{% for diary_data in message %}
                <tr  id='table'>
					<td id='table' class="activity">{{ diary_data.activity }}</td>
					<td id='table' class="type_act">{{ diary_data.type_act }}</td>
                    <td id='table' class="place">{{ diary_data.place }}</td>
					<td id='table' class="date">{{ diary_data.date }}</td>
                    
                </tr>
            {% endfor %}
        </table>
    </div>
<a href="{% url 'Home:schedule' %}"><button  class="btn btn-default" style="margin-top:30px">New Activities</button> </a>
<a href="{% url 'Home:delete' %}"><button  class="btn btn-default" style="margin-top:30px">Delete All</button> </a>
<br><br><br><br>
</body>

</html>

Home/templates/partials/header.html
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ali Yusuf</title>
	<link href="https://fonts.googleapis.com/css?family=Alegreya+Sans" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="/static/css/Style.css">
</head>

<nav class="navbar navbar-expand-lg sticky-top navbar-light"  id="navbar" >
	<a class="navbar-brand" href="{% url 'Home:home' %}">
	<img src="https://image.flaticon.com/icons/svg/25/25694.svg" width="30" height="30" alt="">
	</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0 navbar-right">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Home:home' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Home:experience' %}">Experiences</a>
      </li>
	  <li class="nav-item" >
        <a class="nav-link" href="{% url 'Home:abilities' %}">Abilities</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="{% url 'Home:contact' %}">Contact</a>
      </li>
	   <li class="nav-item">
        <a class="nav-link" href="{% url 'Home:listAct' %}">Activities</a>
      </li>
    </ul>
  </div>
</nav>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>